### ISSUE TITLE
Grunt error

### ISSUE THREAD

**Issue by newaeonweb** [DaftMonk/fullstack-demo#6]
Loading "Gruntfile.js" tasks...ERROR

> > Error: Cannot find module './server/config/local.env'

I can't find the this file. Any help?

**Comment by DaftMonk** [comment]
It's scaffolded by the generator, but ignored by git to keep your environment variables out of source control.
https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/config/_local.env.js

**Comment by var-foo** [comment]
I ran into the same issue, so I put the file you mentioned in and now I get:

```
/server/config/local.env:10
  SESSION_SECRET: "<%= _.slugify(appname) + '-secret' %>",<% if (filters.faceb
                                                          ^
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token <
```

EDIT: I see what's going on here - that's supposed to compile... got it.

**Comment by igalgh** [comment]
+1 I'm bumping in to the same problem when I deploy on linux (works find on osx).
Not sure I understand what's the proposed solution. Is it to 'git add' local.env.js?

**Comment by DaftMonk** [comment]
For local development you would use `local.env.js` to keep track of your environment variables. When deploying, you would manually set the required environment variables.

**Comment by christianhuening** [comment]
I still don't get it. I also inserted the file but got the same syntax-error as var-foo above. What am I supposed to do about it?

**Comment by var-foo** [comment]
@christianhuening the `local.env.js` file is generated when you run the generator, but it is put on a `.gitignore`. If you're not worried about it, you can just take it off the `.gitignore` after you run the generator, or make your own.

@DaftMonk Can you include something like `local.env.js.sample` that is not on a .gitignore so it's easier to figure out what's going on? If you generate a project and then push it to a repo somewhere, anyone that clones it is going to be baffled as to what they're supposed to do to get it running unless they've used this generator before.

**Comment by christianhuening** [comment]
@var-foo thanks! That clarified it. It's now working. Providing an example surely is a good idea.

**Comment by DaftMonk** [comment]
@var-foo Sure, I actually do that on one of my projects. I'll add it to the generator.
